sudo:
  false
language: python
python:
  - '2.7'
addons:
  postgresql: 9.3
  apt:
    packages:
      - fontforge
      - gettext
      - git-core
      - libpcre3
      - libpcre3-dev
      - libpq-dev
      - ttfautohint
# cache:
#   directories:
#     - $HOME/.pip-download-cache
#     - node_modules
script:
  - python manage.py test
  - npm run test
env:
  - PIP_DOWNLOAD_CACHE=$HOME/.pip-download-cache DJANGO_DEBUG=False DJANGO_SECRET_KEY=ZGtvYm90cmF2aXM DJANGO_SETTINGS_MODULE=kobo_playground.settings
install:
  - npm install --save-dev
  - bower install
  - pip install -r requirements.txt
  - python manage.py syncdb --noinput
  - python manage.py migrate --noinput
